// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) => UserModel(
      json['expiresIn'] as int,
      UserInfo.fromJson(json['userInfo'] as Map<String, dynamic>),
      json['refreshIn'] as int,
      json['accessToken'] as String,
    );

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'expiresIn': instance.expiresIn,
      'userInfo': instance.userInfo,
      'refreshIn': instance.refreshIn,
      'accessToken': instance.accessToken,
    };

UserInfo _$UserInfoFromJson(Map<String, dynamic> json) => UserInfo(
      json['address'] as String,
      json['area'] as String,
      json['authorizationCode'] as String,
      (json['balance'] as num).toDouble(),
      json['birthday'] as String,
      json['certCode'] as String,
      json['childStatus'] as int,
      CompanyInfo.fromJson(json['companyInfo'] as Map<String, dynamic>),
      json['companyName'] as String,
      json['createTime'] as String,
      json['email'] as String,
      json['headImgUrl'] as String,
      json['id'] as int,
      json['idCard'] as String,
      json['idCardName'] as String,
      json['ifSet'] as int,
      json['industry'] as String,
      json['lastLoginTime'] as int,
      json['loginIp'] as String,
      json['newPassword'] as String,
      json['nickName'] as String,
      json['owner'] as int,
      json['password'] as String,
      json['payPassword'] as String,
      json['payPasswordLock'] as int,
      json['position'] as String,
      json['reportBuyStatus'] != null ? json['reportBuyStatus'] as int : 0,
      json['reportEndTime'] as String,
      json['reportId'] as String,
      json['reportType'] ?? 1,
      json['rsaEncryption'] as String,
      json['telPhone'] as String,
      json['updateTime'] as String,
      json['userType'] as int,
      json['userValue'] as int,
      json['uuid'] as String,
      json['valid'] as int,
      json['verifiedStatus'] as int,
      json['wechatId'] as String,
      json['workAge'] as String,
    );

Map<String, dynamic> _$UserInfoToJson(UserInfo instance) => <String, dynamic>{
      'address': instance.address,
      'area': instance.area,
      'authorizationCode': instance.authorizationCode,
      'balance': instance.balance,
      'birthday': instance.birthday,
      'certCode': instance.certCode,
      'childStatus': instance.childStatus,
      'companyInfo': instance.companyInfo,
      'companyName': instance.companyName,
      'createTime': instance.createTime,
      'email': instance.email,
      'headImgUrl': instance.headImgUrl,
      'id': instance.id,
      'idCard': instance.idCard,
      'idCardName': instance.idCardName,
      'ifSet': instance.ifSet,
      'industry': instance.industry,
      'lastLoginTime': instance.lastLoginTime,
      'loginIp': instance.loginIp,
      'newPassword': instance.newPassword,
      'nickName': instance.nickName,
      'owner': instance.owner,
      'password': instance.password,
      'payPassword': instance.payPassword,
      'payPasswordLock': instance.payPasswordLock,
      'position': instance.position,
      'reportEndTime': instance.reportEndTime,
      'reportId': instance.reportId,
      'rsaEncryption': instance.rsaEncryption,
      'telPhone': instance.telPhone,
      'updateTime': instance.updateTime,
      'userType': instance.userType,
      'userValue': instance.userValue,
      'uuid': instance.uuid,
      'valid': instance.valid,
      'verifiedStatus': instance.verifiedStatus,
      'wechatId': instance.wechatId,
      'workAge': instance.workAge,
    };

CompanyInfo _$CompanyInfoFromJson(Map<String, dynamic> json) => CompanyInfo(
      json['accountPerson'] as String,
      json['agencyCode'] ?? "",
      json['authorizationCode'] as String,
      (json['balance'] ?? 0).toDouble(),
      json['certCode'] as String,
      json['companyAddress'] as String,
      json['contact'] as String,
      json['contactWay'] as String,
      json['createTime'] as String,
      json['headImgUrl'] as String,
      json['idCardImg'] as String,
      json['lastLoginTime'] as String,
      json['legalPersonName'] as String,
      json['legalPersonPhone'] as String,
      json['licenceImg'] as String,
      json['licenceName'] as String,
      json['loginIp'] as String,
      json['mainIndustry'] as String,
      json['maturityTime'] as String,
      json['name'] as String,
      json['nature'] as String,
      json['refusedReason'] as String,
      json['scale'] as String,
      json['updateTime'] as String,
      json['verifiedStatus'] as int,
      json['vipStatus'] as int,
      json['vipType'] as int,
    );

Map<String, dynamic> _$CompanyInfoToJson(CompanyInfo instance) =>
    <String, dynamic>{
      'accountPerson': instance.accountPerson,
      'agencyCode': instance.agencyCode,
      'authorizationCode': instance.authorizationCode,
      'balance': instance.balance,
      'certCode': instance.certCode,
      'companyAddress': instance.companyAddress,
      'contact': instance.contact,
      'contactWay': instance.contactWay,
      'createTime': instance.createTime,
      'headImgUrl': instance.headImgUrl,
      'idCardImg': instance.idCardImg,
      'lastLoginTime': instance.lastLoginTime,
      'legalPersonName': instance.legalPersonName,
      'legalPersonPhone': instance.legalPersonPhone,
      'licenceImg': instance.licenceImg,
      'licenceName': instance.licenceName,
      'loginIp': instance.loginIp,
      'mainIndustry': instance.mainIndustry,
      'maturityTime': instance.maturityTime,
      'name': instance.name,
      'nature': instance.nature,
      'refusedReason': instance.refusedReason,
      'scale': instance.scale,
      'updateTime': instance.updateTime,
      'verifiedStatus': instance.verifiedStatus,
      'vipStatus': instance.vipStatus,
      'vipType': instance.vipType,
    };
